### ISSUE TITLE
Doesn't Work in 1.4.2-3 (?)

### ISSUE THREAD

**Issue by doodleintime** [Idearum/CrossCode-IntegerScaling#5]
When I put the script file into the game's folder, ran it in powershell, and then open the game's settings menu and went to display, the extra options are not there. This could be because of the newer version of the game. 

I checked in the gui.en_US.json file, and saw no changes made to it at all. Another thing is that the readme.md file has the code changes with formatting instead of gui.en_US.json where it is just one very very long line. I don't know if it was like this on older versions or not.

Now the reason for the (?) in the title is when I right-click on the script file and select run with powershell, a blank powershell window opens up and then not long after, disappears. Nothing shows up in the window, and I don't know if that's normal. I'm running this on Windows 11 Home 22H2 with a Ryzen 7 2700X and a NVIDIA RTX 3070. I can tell more details about my PC specs if necessary.

**Comment by Aemony** [comment]
> Nothing shows up in the window, and I don't know if that's normal.

It both is, and isn’t. The script window wouldn’t appear without user input, however based on your description of it your issue is that Windows is blocking the execution of the script, which is why the window disappears in an instant.

Right click on the ps1 file, open its Properties, and click on the “Unblock” option that should be present towards the bottom. After doing that, try executing it again.

**Comment by Aemony** [comment]
I've added a couple of helper batch files which can also be used to execute the scripts while temporarily bypassing PowerShell's Execution Policy limitations.

**Comment by doodleintime** [comment]
I copied over the newer files and used the .bat file and it worked. Thanks!
